# Generated by Django 3.2.7 on 2021-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
