version: '3.4'

volumes:
  sorted_db:


services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sorted
    volumes:
      - sorted_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 7081:8080

  web:
    build: .
    image: sorted
    command: python manage.py runserver 0.0.0.0:8000
    container_name: sorted_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
